export const API_PATH = {
  LOGIN: getPath("auth/login"),
  RESETPASSWORD: getPath("newPassword"),
  CONFIRMCODE: getPath("verifyCode"),
  RESENDCODE: getPath("resendCode"),
  REGISTER: getPath("auth/register"),
  GETUSER: getPath("users"),
  USERSTATUS: getPath("userStatus"),
  CREATEUSER: getPath("users"),
  CREATEHOTEL: getPath("accommodation"),
  BOOKING: getPath("order"),
  UPDATEHOTEL: getPath("accommodationUpdate"),
  GETHOTEL: getPath("accommodation"),
  GETROOM: getPath("room"),
  CREATEROOM: getPath("room"),
  UPDATEROOM: getPath("roomUpdate"),
  GETHOLIDAY: getPath("holidays"),
  CREATEHOLIDAY: getPath("holidays"),
  UPDATEHOLIDAY: getPath("holidaysUpdate"),
  GETHOLIDAYDETAIL: getPath("holidays/:id"),
  DELETEHOLIDAY: getPath("holidays"),
  GETDISCOUNT: getPath("discount"),
  CREATEDISCOUNT: getPath("discount"),
  UPDATEDISCOUNT: getPath("discountUpdate"),
  GETDISCOUNTDETAIL: getPath("discount/:id"),
  STATUSDISCOUNT: getPath("discountStatus"),
  GETORDER: getPath("order"),
  CREATEORDER: getPath("order"),
  UPDATEORDER: getPath("orderUpdate"),
  PAYSTATUS: getPath("paymentStatus"),
  GETORDERDETAIL: getPath("order/:id"),
  GETINVOICE: getPath("invoices"),
  GETINVOICEDETAIL: getPath("invoices/:id"),
  UPDATEUSER: getPath("users"),
  ADDIMG: getPath("img/upload"),
  VERIFY_EMAIL: (token) => getPath(`verify-email?token=${token}`),
  ALLBANKS: getPath("banks"),
  STATUSROOM: getPath("roomStatus"),
  STATUSHOTEL: getPath("accommodationStatus"),
  GETDETAIL: getPath("room/:id"),
  GETHOTELDETAIL: getPath("accommodation/:id"),
  LOGOUT: getPath("auth/logout"),
  REVENUE: getPath("revenue"),
  GETBENEFITS: getPath("benefit"),
  CREATEBENEFITS: getPath("benefit"),
};

function getPath(path) {
  return `https://be-trothalo.onrender.com/api/v1/${path}`;
}

export default API_PATH;
